"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const taskController_1 = require("../controllers/taskController");
const router = (0, express_1.Router)();
router.get('/', taskController_1.taskController.getAllTasks);
router.get('/:id', taskController_1.taskController.getTaskById);
router.post('/', taskController_1.taskController.createTask);
router.patch('/:id', taskController_1.taskController.updateTask);
router.delete('/:id', taskController_1.taskController.deleteTask);
exports.default = router;
